// Generated by scripts/optimize-media.mjs.
export type GeneratedVideoDescriptor = Readonly<{ poster: string; mp4: string; webm: string | null }>;
export const generatedVideo: GeneratedVideoDescriptor = {
  "poster": "/media/team-video-poster.webp",
  "mp4": "/media/team-video-720.mp4",
  "webm": "/media/team-video-720.webm"
};
